name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install server deps
        working-directory: server
        run: npm ci || npm install

      - name: Install client deps
        working-directory: client
        run: npm ci || npm install

      - name: Lint client
        working-directory: client
        run: npm run lint

      - name: Build client
        working-directory: client
        run: npm run build
